version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - app-cache:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    ports:
      - 5000:5000
    networks:
      - f1db
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  f1db:
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    volumes:
      - f1db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: jolpica
      POSTGRES_PASSWORD: postgres
    ports:
       - 9999:5432
    networks:
      - f1db
  redis:
    image: redis
    networks:
      - f1db
    ports:
       - 6379:6379
       
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  oteltui: # To access run `docker attach otel-tui`
    image: ymtdzzz/otel-tui:latest
    container_name: otel-tui
    stdin_open: true
    tty: true
    entrypoint: ["/otel-tui", "--enable-zipkin"]
    networks:
      - f1db

volumes:
  f1db-data:
  app-cache:
networks:
  f1db:
